from tkinter import *
class On_screen_keyboard:
    window = Tk()
    window.geometry("500x500")
    window.title("Keyboard")
    def __init__(self):
        self.keyboard()
    ButtonQ = Button(window, text="q", relief=FLAT, height=2, width=2, background= "light blue").place(x=0, y=300)
    ButtonW = Button(window, text="w", relief=FLAT, height=2, width=2, background="light blue").place(x=25, y=300)
    ButtonE = Button(window, text="e", relief=FLAT, height=2, width=2, background="light blue").place(x=50, y=300)
    ButtonR = Button(window, text="r", relief=FLAT, height=2, width=2, background="light blue").place(x=75, y=300)
    ButtonT = Button(window, text="t", relief=FLAT, height=2, width=2, background="light blue").place(x=100, y=300)
    ButtonY = Button(window, text="y", relief=FLAT, height=2, width=2, background="light blue").place(x=125, y=300)
    ButtonU = Button(window, text="u", relief=FLAT, height=2, width=2, background="light blue").place(x=150, y=300)
    ButtonI = Button(window, text="i", relief=FLAT, height=2, width=2, background="light blue").place(x=175, y=300)
    ButtonO = Button(window, text="o", relief=FLAT, height=2, width=2, background="light blue").place(x=200, y=300)
    ButtonP = Button(window, text="p", relief=FLAT, height=2, width=2, background="light blue").place(x=225, y=300)
    ButtonA = Button(window, text="a", relief=FLAT, height=2, width=2, background="light blue").place(x=0, y=345)
    ButtonS = Button(window, text="s", relief=FLAT, height=2, width=2, background="light blue").place(x=25, y=345)
    ButtonD = Button(window, text="d", relief=FLAT, height=2, width=2, background="light blue").place(x=50, y=345)
    ButtonF = Button(window, text="f", relief=FLAT, height=2, width=2, background="light blue").place(x=75, y=345)
    ButtonG = Button(window, text="g", relief=FLAT, height=2, width=2, background="light blue").place(x=100, y=345)
    ButtonH = Button(window, text="h", relief=FLAT, height=2, width=2, background="light blue").place(x=125, y=345)
    ButtonJ = Button(window, text="j", relief=FLAT, height=2, width=2, background="light blue").place(x=150, y=345)
    ButtonK = Button(window, text="k", relief=FLAT, height=2, width=2, background="light blue").place(x=175, y=345)
    ButtonL = Button(window, text="l", relief=FLAT, height=2, width=2, background="light blue").place(x=200, y=345)
    Buttonç = Button(window, text="ç", relief=FLAT, height=2, width=2, background="light blue").place(x=225, y=345)
    ButtonZ = Button(window, text="z", relief=FLAT, height=2, width=2, background="light blue").place(x=0, y=390)
    ButtonX = Button(window, text="x", relief=FLAT, height=2, width=2, background="light blue").place(x=25, y=390)
    ButtonC = Button(window, text="c", relief=FLAT, height=2, width=2, background="light blue").place(x=50, y=390)
    ButtonV = Button(window, text="v", relief=FLAT, height=2, width=2, background="light blue").place(x=75, y=390)
    ButtonB = Button(window, text="b", relief=FLAT, height=2, width=2, background="light blue").place(x=100, y=390)
    ButtonN = Button(window, text="n", relief=FLAT, height=2, width=2, background="light blue").place(x=125, y=390)
    ButtonM = Button(window, text="m", relief=FLAT, height=2, width=2, background="light blue").place(x=150, y=390)
    ButtonSpace = Button(window, text=" ", relief=FLAT, height=2, width=10, background="light blue").place(x=100, y=435)
    window.mainloop()